### ISSUE TITLE
Expose more user info

### ISSUE THREAD

**Issue by 360noscope** [jlguenego/node-expose-sspi#1]
Hi this is not really urgent but i suggest  to expose more AD user info more such as Firstname, Surname :) really loves this module

**Comment by jlguenego** [comment]
Thanks for you encouragement,
I need to investigate what Microsoft can expose about Active Directory info.

**Comment by 360noscope** [comment]
> 
> 
> Thanks for you encouragement,
> I need to investigate what Microsoft can expose about Active Directory info.

Mostly they provided a ton of data via ldap.

**Comment by jlguenego** [comment]
I did it ;)

It was a big development, but now you can access the Active Directory Domain Controller via the ADSI Microsoft interface. I have chosen this interface because there is no password to provide. The authentication is done by the HTTP server account. (LDAP interface needs explicit credentials... boooh)

So if your computer is joined to a domain, you can test it... ;)
node-expose-sspi version 0.1.1

Tell me if any bug due to these big changes.

If not, I will close this issue.
