### ISSUE TITLE
Question: Cannot work with useActiveDirectory=true.

### ISSUE THREAD

**Issue by rbartholomay** [jlguenego/node-expose-sspi#4]
Hi there...

I have some questions:

When i put the sample-code on the server it will only run then useActiveDirectory=false and cookies=true. 
How can i check on the server that there is a reachable Active Directory?  And will the combination of useActiveDirectory=true and cookies=true never run?

I am not familar with the complete technic behind the auth...

best wishes...
   rené...

**Comment by jlguenego** [comment]
I try to explain on the technical point of view:

When a user tries to authenticate with NTLM protocol, it does a first HTTP request, and then a second HTTP request.
In real world, these two consecutives requests are done very quickly, the second just after the first one.

However, when two users A and B try to authenticate at the same time, it is possible that user A does the first request and then user B does also it first request before user A performs the second request. In this case, the NTLM security context is broken and an error is raised.

So I added an async mutex to avoid this. And I added also a cookie method in order to have a NTLM security handle per user.

There is also this new functionnality, the Active Directory. The Active Directory must be also accessed with a simple mutex to avoid too many requests at the same time on it. The Active Directory access is done through a COM interface.

The problem is there is a windows limitation (the crash you had before... remember) : the SSPI interface needs also a COM interface and the Active Directory use another one. And both activated at the same time (by two different user A and B) lead to a crash... :O((((

So that's why I added this constraint : **You cannot use Active Directory (ADSI) and SSPI at the same time.**

Now if you have this question (and raised an issue). This is not very good regarding the UX (DX) point of view. Another way is to force `useCookies=false` when `useActiveDirectory=true`... ;) So you don't notice (and do not have question...)

I propose to do that.

**Comment by rbartholomay** [comment]
Thank you very much for explaining this! 👍

Best wishes, René

**Comment by jlguenego** [comment]
Thanks 😃

**Comment by jlguenego** [comment]
I am proud to tell you that I identify the crash reason : I was using CoUninitialize() with parallelism... so if another request was in parallel doing stuff with AD, crash...

I solve this bug.

Since 0.1.22 it is possible to freely use "useCookie" in every situation.

**Comment by rbartholomay** [comment]
Wow! 😮 I will try that tomorrow... 👍
