### ISSUE TITLE
Tried fetch for Kerberos

### ISSUE THREAD

**Issue by StuartLoria** [jlguenego/node-expose-sspi#6]
I tried using the code to process a Kerberos negotiation but the base64 string created by the InitializeSecurityContext (with targetDataRep = SECPKG_CRED_OUTBOUND) and the AcquireCredentialsHandle (with targetDataRep = SECURITY_NATIVE_DREP) is not working.
I creates a string value but the server rejects it.
I tried with a different node component (but compiled for a node version that is not convenient for me 11.15.0) and it works against the same address, an SVC .net web service hosted in IIS with Windows Authentication with the Provider = Negotiate.
I tried against without the SSL certificate, this component does not work but the other component for node 11.15.0 does, so I think the Kerberos values used to generate the base64 string are wrong.

**Comment by jlguenego** [comment]
I try to reformule your issue :
1) it is related to the `new sso.Client().fetch()`
2) the url contacted is hosted on a IIS server with a SVC .net web service.

Now they are something not clear to me and therefore I need more info:
1) please indicate the version of `node-expose-sspi`.
2) The `node-expose-sspi` module uses the `debug` npm module for tracing things. This morning I have added more debug trace in order to better unerstand the different situations. Please `npm i node-expose-sspi@latest` (0.1.15)
please run your scenario with trace by setting the DEBUG env variable to trace all stuff from node-expose-sspi : `set DEBUG=node-expose-sspi:*`
3) Copy paste the traces.

In fact, the most important is to see how the communication is done between the client and server.

4) You mention another tool. Please tell what it is, with the version.
5) Please indicate your windows version
6) The client computer is on a domain ?
7) is the server computer on the same domain ?
8) Is the server `service principal name` declared ?
9) Is it possible I reproduce at home your bug on my windows ?

We need to understand exactly what the problem is.

**Comment by jlguenego** [comment]
I saw a not expected behavior, which can be related (even be the cause) to this issue. The client should send a Kerberos token, but send a NTLM one. I am going to investigate.

**Comment by jlguenego** [comment]
This is the trace I have. Note that if the ticket does not start with YII, but TlR then it is NTLM.

```
D:\formation\node-expose-sspi\examples\client>node client.js
  node-expose-sspi:client start response.headers Headers {
  [Symbol(map)]: [Object: null prototype] {
    'x-powered-by': [ 'Express' ],
    'www-authenticate': [ 'Negotiate' ],
    date: [ 'Fri, 10 Apr 2020 12:41:26 GMT' ],
    connection: [ 'close' ],
    'content-length': [ '0' ]
  }
} +0ms
  node-expose-sspi:client cookieList:  {} +4ms
  node-expose-sspi:client starting negotiate auth +5ms
  node-expose-sspi:client first requestInit.headers {
  Authorization: 'Negotiate TlRMTVNTUAABAAAAl7II4gMAAwAwAAAACAAIACgAAAAKAGNFAAAAD0NIT1VDSE9VSkxH'
} +21ms
  node-expose-sspi:client first response.headers Headers {
  [Symbol(map)]: [Object: null prototype] {
    'x-powered-by': [ 'Express' ],
    'www-authenticate': [
      'Negotiate TlRMTVNTUAACAAAABgAGADgAAAAVgonigGnoA8FAJagAAAAAAAAAAH4AfgA+AAAACgDuQgAAAA9KAEwARwACAAYASgBMAEcAAQAOAE0AVQBTAEUAVABUAEUABAASAGoAbABnAC4AbABvAGMAYQBsAAMAIgBtAHUAcwBlAHQAdABlAC4AagBsAGcALgBsAG8AYwBhAGwABQASAGoAbABnAC4AbABvAGMAYQBsAAcACAAQ3WBZNQ/WAQAAAAA='
    ],
    date: [ 'Fri, 10 Apr 2020 12:41:26 GMT' ],
    connection: [ 'close' ],
    'content-length': [ '0' ]
  }
} +48ms
  node-expose-sspi:client other requestInit.headers {
  Authorization: 'Negotiate TlRMTVNTUAADAAAAGAAYAHoAAAAKAQoBkgAAAAYABgBYAAAADAAMAF4AAAAQABAAagAAABAAEACcAQAAFYKI4goAY0UAAAAPj+YN6j8uNAZwL+X6jMDZlkoATABHAGoAbABvAHUAaQBzAEMASABPAFUAQwBIAE8AVQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADv7orfrH/F85syqJGY7seTAQEAAAAAAAAQ3WBZNQ/WAe7VorT9D4KVAAAAAAIABgBKAEwARwABAA4ATQBVAFMARQBUAFQARQAEABIAagBsAGcALgBsAG8AYwBhAGwAAwAiAG0AdQBzAGUAdAB0AGUALgBqAGwAZwAuAGwAbwBjAGEAbAAFABIAagBsAGcALgBsAG8AYwBhAGwABwAIABDdYFk1D9YBBgAEAAIAAAAIADAAMAAAAAAAAAABAAAAACAAAOH4mweSwArhs4WESdQz9GyOHi4Za9f9SFfGdq2u3PasCgAQAAAAAAAAAAAAAAAAAAAAAAAJAAgAawBpAGsAaQAAAAAAAAAAACCQnty3fgLTlBNUiU0G6bs='
} +3ms
  node-expose-sspi:client other response.headers Headers {
  [Symbol(map)]: [Object: null prototype] {
    'x-powered-by': [ 'Express' ],
    'www-authenticate': [ 'Negotiate' ],
    'content-type': [ 'application/json; charset=utf-8' ],
    'content-length': [ '2271' ],
    etag: [ 'W/"8df-Uh1/XdXILcLRiE3rzng6/DwQUz4"' ],
    date: [ 'Fri, 10 Apr 2020 12:41:26 GMT' ],
    connection: [ 'close' ]
  }
} +523ms
  node-expose-sspi:client handleAuth: end +1ms
json:  {
  toto: 123,
  sso: {
    method: 'NTLM',
    user: {
      domain: 'JLG',
      name: 'jlouis',
      displayName: 'jlouis',
      groups: [Array],
      sid: 'S-1-5-21-2022955591-1730574677-3210790899-1103',
      adUser: [Object]
    }
  }
}
```

**Comment by jlguenego** [comment]
I can confirm the bug : the client was always sending NTLM request even when Kerberos would be more appropriate (Negotiate protocol). This is because the targetName (which should reflect the SPN) was always set to `'kiki'`... :smiley:

So I corrected this behavior and now the targetName is always equals to the expected SPN: `'HTTP/' + domain`

**Comment by jlguenego** [comment]
Please test the 0.1.16 version and close the bug if solved.

**Comment by StuartLoria** [comment]
I tested again with the latest version but it did not work, in order to make it work I had to hard-code **targetName** with the following: _'HTTP/ServerName'_ instead of _'HTTP/WebSiteDomain'_ as the code was inferring from the URL.
Then it took only 2 requests to resolve the Negotiation, the value of the base64 string changed as well, it was longer and it started with this: _'YIIIwQYGKwYBBQUCoIIItTCCCLGgMDA...'_
Let me know what you make out of this information.

**Comment by jlguenego** [comment]
I have identified a bug in the `getSPNFromURI` function.

From the following doc : https://support.microsoft.com/en-us/help/4551934/kerberos-failures-in-internet-explorer
Part **Does IE use the expected SPN**

It is written that the domain name indicated in the url must be converted to the server name.
Converting any CNAME to A field from the DNS.

So now it is done.

Can you please try with version 0.1.18 ?
Thanks ;)

**Comment by jlguenego** [comment]
Hi Stuart, other things came and now the version is 0.1.23. Please use the latest to test. And let me know if I can close this issue. Thanks.

**Comment by jlguenego** [comment]
Hi Stuart, any news ? The last version is 0.1.24. Please let me know if I can close this issue. Thanks.

**Comment by StuartLoria** [comment]
I have not had time to test, but I will this week and let you know

**Comment by jlguenego** [comment]
Considered as corrected.
