### ISSUE TITLE
32-bit Compatibility 

### ISSUE THREAD

**Issue by acecoder93** [jlguenego/node-expose-sspi#9]
I face an error when running the library with nodejs 32-bit, please see console response: "\node_modules\node-expose-sspi\lib\api.node is not a valid Win32 application."

Is it possible to update the library, so that it is compatible with a 32-bit environment (nodejs and Windows OS)?

**Comment by jlguenego** [comment]
Yes it is. Will do i soon ;)

**Comment by jlguenego** [comment]
tadammm !!! it is done and release in 0.1.24 😃 

So now I build both ia32 and x64 architectures. and when you install, in the postinstall I copy the api.node file at the right place so you can use it.

Warning: you need to run npm install on the target platform, or at least the postinstall.

Please test and tell me if I can close this issue.

**Comment by acecoder93** [comment]
Thank you for your help!
1) I was unable to fully test it as I am running nodejs 32-bit on Windows 64-bit. Is it possible for the library to check the architecture of nodejs or make this an attribute that the user can adjust (32 bit vs 64 bit)?

**Comment by jlguenego** [comment]
**TL;DR : There is no bug, it works well. but you need a manual step:**

**run `npm run postinstall` in the `node-expose-sspi` module if you change your platform, or simply remove the `node_modules` directory and run `npm i`.**

I can do a 0.1.25 which does not necessite this step. Would you like me to do it ?

Detailed answer:

I have installed on my computer [nvm for windows](https://github.com/coreybutler/nvm-windows) in order to be able to test many node version, 32 or 64 bits.

Then I did:
```cmd
nvm install latest 32
... // install node 14.0.0 32 bit (at this time 28 apr 2020, latest=14.0.0)

nvm install latest 64
... // install node 14.0.0 64 bit

nvm use 14.0.0 64
```

Then I created a test project as indicated in the [README.md](https://github.com/jlguenego/node-expose-sspi/blob/master/README.md) file.

```
D:\formation>nvm use 14.0.0 64
Now using node v14.0.0 (64-bit)

D:\formation>node -p process.arch
x64

D:\formation>mkdir myproject

D:\formation>cd myproject

D:\formation\myproject>npm init -y
Wrote to D:\formation\myproject\package.json:

{
  "name": "myproject",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}



D:\formation\myproject>npm i node-expose-sspi@0.1.24 express

> node-expose-sspi@0.1.24 postinstall D:\formation\myproject\node_modules\node-expose-sspi
> node ./scripts/install.js

installing x64 api.node
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN myproject@1.0.0 No description
npm WARN myproject@1.0.0 No repository field.

+ express@4.17.1
+ node-expose-sspi@0.1.24
added 57 packages from 40 contributors and audited 137 packages in 4.228s
found 0 vulnerabilities
```

I wrote the `server.js` file like on the README.
```js
const express = require('express');
const { sso } = require('node-expose-sspi');

const app = express();
app.use(sso.auth());

app.use((req, res, next) => {
  res.json({
    sso: req.sso,
  });
});

app.listen(3000, () => console.log('Server started on port 3000'));
```

Then I started the project and all went well.
```
D:\formation\myproject>node server.js
Server started on port 3000
^C
D:\formation\myproject>

Now I switched on 32bits and I got your problem:

```
D:\formation\myproject>nvm use 14.0.0 32
Now using node v14.0.0 (32-bit)

D:\formation\myproject>node -p process.arch
ia32

D:\formation\myproject>node server.js
internal/modules/cjs/loader.js:1235
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: \\?\D:\formation\myproject\node_modules\node-expose-sspi\lib\api.node is not a valid Win32 application.
\\?\D:\formation\myproject\node_modules\node-expose-sspi\lib\api.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1235:18)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\formation\myproject\node_modules\node-expose-sspi\dist\index.js:13:10)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
```

Hahaaaaaa... How to make it works ???? 🥰 

Answer: like this ... see below.

```
D:\formation\myproject>cd node_modules

D:\formation\myproject\node_modules>cd node-expose-sspi

D:\formation\myproject\node_modules\node-expose-sspi>npm run postinstall

> node-expose-sspi@0.1.24 postinstall D:\formation\myproject\node_modules\node-expose-sspi
> node ./scripts/install.js

installing ia32 api.node

D:\formation\myproject\node_modules\node-expose-sspi>cd ..

D:\formation\myproject\node_modules>cd ..

D:\formation\myproject>node server.js
Server started on port 3000
^C
D:\formation\myproject>
```

It works !!! ;)

**Comment by jlguenego** [comment]
You know what ? version of today 0.1.25 works for both ia32 and x64 **without modifying anything**. I think you will like it 😄 

Try it and close this issue if you agree.

Cheers,

**Comment by acecoder93** [comment]
Thank you for the new version. 0.1.25 fixes the issue for "api.node is not a valid Win32 application." and allows for 32-bit and 64-bit nodejs compatibility; however a new issue comes up after I run the script to test it.

I tried running the script with both 32-bit and 64-bit node and received the following error:
**"BadRequestError: Error while doing SSO: AcceptSecurityContext: SECURITY_STATUS incorrect(<0): (error code: 0x80090308) The token supplied to the function is invalid.**

**Comment by jlguenego** [comment]
ok, then I close this issue.

Regarding the "BadRequestError", it says what it says : bad request. Your HTTP client did not send the right token. Most of the time this error occurs first time the website load, and then it synchronizes and there is no more error. If this is your case then it is not a bug inside the node-expose-sspi library but in Microsoft SSPI itself. I cannot do anything about it.

However, if you have this error in a repetitive manner, I suggest you to open a different issue, and explain exactly in which conditions this error occurs.

Thanks.
